### ISSUE TITLE
White Screen with firefox add on "no script"

### ISSUE THREAD

**Issue by margoux** [Gix075/jqueryIntroLoader#8]
great loader, but when using firefox add-on noscript I have a white page. No content is displayed.

thanks for more information, margoux

**Comment by Gix075** [comment]
I never used that add-on, but reading on web i saw that the "noscript" Firefox add-on blocks all javascript/jquery execution.  So the html element that has the class *introLoading* can't be manipulated by the plugin.  If you look at the css you can see that the *introLoading* class defines a white fixed element placed over the page.

```css
.introLoader,
.introLoading {
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  overflow: hidden;
  z-index: 9999;
}
.introLoading {
  background-color: #fff;
}
```

If javascript it's blocked, plugin can't remove the class from the element on window load event. 
So, to solve your issue, you can try to remove the *introLoading* class from the html element, but i'm not sure that this is the correct solution. Just try and let me know.
I hope this can help you.
